### ISSUE TITLE
"Próximo evento" mais inteligente

### ISSUE THREAD

**Issue by marado** [transparenciahackday/datewithdata.pt#1]
Ter a data do próximo evento configurável, e ajustar o texto do site para não indicar uma data passada (ou mudando para "Brevemente", ou mudando "próximo evento" para "último evento", quando a data é no passado).

**Comment by rlafuente** [comment]
Bem apontado! (e lamento a estúpida demora em responder a este ticket)

A nossa workflow para isto é muito manual -- editamos o HTML diretamente, e normalmente apenas decidimos o tema do DWD na semana anterior ao evento. Como achas que poderíamos melhorar este workflow sem implicar muito trabalho adicional?

**Comment by marado** [comment]
Por mim, o workflow até pode ser o mesmo. A diferença seria que passavas a ter uma variável com a data, e continuavas a editar manualmente.

A data passa a ser automaticamente avaliada, e o texto mostrado varia se estamos no futuro ou no passado.

**Comment by rlafuente** [comment]
Certo. Talvez se consiga alinhar isto com JS e uma lista de datas (introduzir a dependência de PHP aqui é um pouco overkill)

**Comment by marado** [comment]
Estava a pensar nisto com JS, não já vantagem ou necessidade de ter isto
feito server-side.
