### ISSUE TITLE
Retirar a featured image de posts onde não faz sentido (ex. Airbnb)

### ISSUE THREAD

**Issue by rlafuente** [transparenciahackday/datewithdata.pt#9]
Talvez uma opção `RemoveFeaturedImage` nos metadados do post?

**Comment by aiscarvalho** [comment]
Está retirada. Aparecia no post com a tag Ensaio e nesse não faz sentido a imagem aparecer na página individual, apenas na página do blog (lista de posts).
Incluí uma nota rápida no README mas depois podemos documentar melhor.
